project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - text: "home"
        href: eam-home.qmd
      - text: "theory"
        href: eam-slide.qmd
      - text: "practice"
        href: eam-workshop.qmd
      - text: "credits"
        href: eam-credits.qmd

format:
  html: 
    theme: cosmo
    fontsize: 1.12em
    linestretch: 1.7
    mainfont: Helvetica Neue
    css: styles.css
    toc: true
    grid:
      sidebar-width: 100px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1rem

